### PR TITLE
fixed: broken coupon view in the shopware administration and styling fix

### PR DESCRIPTION
**Pull request by LouisEiermann**
- button styling of button inside coupon view in the administration
- deleted unnecessary parent() inside coupon view in the administration

### CODE REVIEW

**Comment by Vhulcan** [comment]
@Vildulv Why has PR been closed? The issue is still not fixed in the 3.1.0 release.

**Comment by Vildulv** [comment]
@Vhulcan  Sorry, GitHub did it automatically. Reopened it again

**Comment by nussjustin-hmmh** [comment]
We have been running into the same problem. Any plan on when this will be fixed / merged?

**Comment by wannevancamp** [comment]
@Vildulv, I don't think this issue can be closed. It's still an issue.

**Comment by Vildulv** [comment]
> We have been running into the same problem. Any plan on when this will be fixed / merged?

@nussjustin-hmmh In version 3.1.1 this was fixed.

**Pull request closed without merging**
